{% set name = "zope.hookable" %}
{% set version = "8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zope_hookable-{{ version }}.tar.gz
  sha256: 2e7c22c9eefa831206771f70e2d8b45608d304a87ba771ff99b2358aae214de3

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-build_isolation . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - zope.proxy

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/zopefoundation/zope.hookable
  license: ZPL-2.1
  license_file: LICENSE.txt
  summary: supports the efficient creation of “hookable” objects, which are callable objects that are meant to be optionally replaced.
  description: |
    This package supports the efficient creation of “hookable” objects, which
    are callable objects that are meant to be optionally replaced.
    The idea is that you create a function that does some default thing and make
    it hookable. Later, someone can modify what it does by calling its sethook
    method and changing its implementation. All users of the function, including
    those that imported it, will see the change.
  doc_url: https://zopehookable.readthedocs.io
  dev_url: https://github.com/zopefoundation/zope.hookable

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
